changelog:
  exclude:
    labels:
      - rl_ignore
    authors:
  categories:
    - title: Features
      labels:
        - rl_feature
    - title: Fixes
      labels:
        - rl_fixes
    - title: Changes
      labels:
        - rl_changes