changelog:
  exclude:
    labels:
      - rl_ignore
  categories:
    - title: Features
      labels:
        - rl_features
    - title: Fixes
      labels:
        - rl_fixes
    - title: Changes
      labels:
        - rl_changes
